### PR TITLE
Minor fixes

### LINKED ISSUE #506: CTL only supports RGBA
The plugin only supports RGBA images but declares that it supports all kind of clip types:
https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/process/color/CTL/src/CTLPluginFactory.cpp#L67

### LINKED ISSUE #507: colorcubeviewer bad uid
https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/display/ColorCubeViewer/src/mainEntry.cpp
Should be tuttle.colorcubeviewer instead of tuttle.colorcube which already exist.

### PR DESCRIPTION
**Pull request by fabiencastan**
Fix #506 
Fix #507

### CODE REVIEW

**Comment by cchampet** [comment]
The CI failed because of the python3 jobs : the SWIG option "-py3" is not recognized. According to the [SWIG Releases](http://www.swig.org/Release/CHANGES), this option is available since version 1.3.37 (13 January 2009). The SWIG version found in the Travis job is 2.0.4...
Ok the problem is because when building sequenceParser binding, the '-py3' option is passed to the SWIG_FLAGS used to generated the java binding... ERROR !
Need to fix here: https://github.com/mikrosimage/sequenceparser/blob/develop/src/CMakeLists.txt#L59
I will do it in this PR.

**Comment by fabiencastan** [comment]
It's also here:
https://github.com/tuttleofx/TuttleOFX/blob/3b5d0b137fb5edb6f0b8b51c22b19d254868db28/libraries/tuttle/CMakeLists.txt#L148

I don't understand your conclusion. We need to set this flag to build the python3 variant and this option should be recognized by swig on travis (regarding the version used). And it was working before, so it's really strange.

Maybe we can use `swig3.0` instead of `swig` in the apt packages.

**Comment by fabiencastan** [comment]
Ok, I got your point. This swig flag is specific to python and should not be used for java.

**Comment by cchampet** [comment]
My mistake: I pull develop branch on this PR...
See PR #515

**Pull request closed without merging**
