### PR TITLE
CMake: numpy is an optional dependency

### PR DESCRIPTION
**Pull request by cchampet**

### CODE REVIEW

**Comment by cchampet** [comment]
I can't manage SWIG interfaces like:
* libraries/tuttle/src/tuttle/host/OutputBufferWrapper.
* libraries/tuttle/src/tuttle/host/InputBufferWrapper.
* libraries/tuttle/src/tuttle/host/attribute/Image.

without numpy.

Any ideas @fabiencastan ?

**Comment by fabiencastan** [comment]
Just disable those parts in the binding without numpy.

**Comment by cchampet** [comment]
In CMake files, I have NUMPY_FOUND.
In SWIG interface, I have...?

**Comment by fabiencastan** [comment]
You need to add the define WITHOUT_NUMPY in cmake.
Then you should be able to do:
OutputBufferWrapper.i
```
#ifndef WITHOUT_NUMPY

// all your .i content

#endif
```

**Comment by cchampet** [comment]
Can be merge ? @fabiencastan

**Comment by cchampet** [comment]
Yes I tested it and it works: I have ```getImage``` function in python even if I don't have numpy.

**Pull request merged**
