### PR TITLE
rawreader: dev white balance

### PR DESCRIPTION
**Pull request by cchampet**
To do:
* strange value of _paramShutter.  
https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/io/Raw/src/reader/RawReaderPlugin.cpp#L130
* 3 parameters to manually set white balance => Kelvin.  
It depends on the colorspace... Not easy to compute.

### CODE REVIEW

**Comment by cchampet** [comment]
Need to expose the input white balance in Kelvin: find a formula to compute something like:
K = xR + xG + xB

**Comment by cchampet** [comment]
The plugin print some value: remove them.
Check here https://github.com/tuttleofx/TuttleOFX/blob/develop/plugins/image/io/Raw/src/reader/RawReaderPlugin.cpp#L98

**Comment by cchampet** [comment]
Up plugin version.

**Comment by fabiencastan** [comment]
Could be merged?

**Comment by cchampet** [comment]
I would like to remove some print before merged (see comment above). I will tell you when it will be done.

**Pull request merged**
